version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/fastapi
      - JWT_SECRET=secret
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
  db:
    image: postgres:13.16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
